# Generated by Django 2.1 on 2018-08-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, null=True)),
                ('school', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('eventType', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
