# Generated by Django 2.1 on 2018-09-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180901_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='eventTypeID',
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventtypes',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
