# Generated by Django 2.1 on 2018-09-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180902_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='city',
        ),
    ]
