# Generated by Django 2.1 on 2018-09-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
