# Generated by Django 2.1 on 2018-09-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180903_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
