# Generated by Django 2.1 on 2018-09-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180903_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.TextField(null=True, unique=True),
        ),
    ]
