# Generated by Django 2.1 on 2018-09-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180901_0615'),
        ('register', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
